//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.235.
// 
#pragma warning disable 1591

namespace ICP_Soap_Interface_Tester.ScadaSoapService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SCADASoapServicePortBinding", Namespace="http://progauge.scada.com")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(getTagValueLatestResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(getTagValueLatest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(getVersionResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(getVersion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(getSystemTimeResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(getSystemTime))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(getTagValuesLatest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(getEquipmentList))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(getTagList))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(getTagValuesAsOf))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InvalidTagNameException))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DatabaseDownException))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(getTagValueAsOfResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(getTagValueAsOf))]
    public partial class SCADASoapService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getEquipmentListOperationCompleted;
        
        private System.Threading.SendOrPostCallback getSystemTimeOperationCompleted;
        
        private System.Threading.SendOrPostCallback getTagListOperationCompleted;
        
        private System.Threading.SendOrPostCallback getTagValueAsOfOperationCompleted;
        
        private System.Threading.SendOrPostCallback getTagValuesAsOfOperationCompleted;
        
        private System.Threading.SendOrPostCallback getTagValueLatestOperationCompleted;
        
        private System.Threading.SendOrPostCallback getTagValuesLatestOperationCompleted;
        
        private System.Threading.SendOrPostCallback getVersionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SCADASoapService() {
            this.Url = global::ICP_Soap_Interface_Tester.Properties.Settings.Default.ICP_Soap_Interface_Tester_ScadaSoapService_SCADASoapService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getEquipmentListCompletedEventHandler getEquipmentListCompleted;
        
        /// <remarks/>
        public event getSystemTimeCompletedEventHandler getSystemTimeCompleted;
        
        /// <remarks/>
        public event getTagListCompletedEventHandler getTagListCompleted;
        
        /// <remarks/>
        public event getTagValueAsOfCompletedEventHandler getTagValueAsOfCompleted;
        
        /// <remarks/>
        public event getTagValuesAsOfCompletedEventHandler getTagValuesAsOfCompleted;
        
        /// <remarks/>
        public event getTagValueLatestCompletedEventHandler getTagValueLatestCompleted;
        
        /// <remarks/>
        public event getTagValuesLatestCompletedEventHandler getTagValuesLatestCompleted;
        
        /// <remarks/>
        public event getVersionCompletedEventHandler getVersionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://progauge.scada.com", ResponseNamespace="http://progauge.scada.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("equipment", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] getEquipmentList() {
            object[] results = this.Invoke("getEquipmentList", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void getEquipmentListAsync() {
            this.getEquipmentListAsync(null);
        }
        
        /// <remarks/>
        public void getEquipmentListAsync(object userState) {
            if ((this.getEquipmentListOperationCompleted == null)) {
                this.getEquipmentListOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetEquipmentListOperationCompleted);
            }
            this.InvokeAsync("getEquipmentList", new object[0], this.getEquipmentListOperationCompleted, userState);
        }
        
        private void OngetEquipmentListOperationCompleted(object arg) {
            if ((this.getEquipmentListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getEquipmentListCompleted(this, new getEquipmentListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://progauge.scada.com", ResponseNamespace="http://progauge.scada.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void getSystemTime([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out System.DateTime systemTime, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] out bool systemTimeSpecified) {
            object[] results = this.Invoke("getSystemTime", new object[0]);
            systemTime = ((System.DateTime)(results[0]));
            systemTimeSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void getSystemTimeAsync() {
            this.getSystemTimeAsync(null);
        }
        
        /// <remarks/>
        public void getSystemTimeAsync(object userState) {
            if ((this.getSystemTimeOperationCompleted == null)) {
                this.getSystemTimeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSystemTimeOperationCompleted);
            }
            this.InvokeAsync("getSystemTime", new object[0], this.getSystemTimeOperationCompleted, userState);
        }
        
        private void OngetSystemTimeOperationCompleted(object arg) {
            if ((this.getSystemTimeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSystemTimeCompleted(this, new getSystemTimeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://progauge.scada.com", ResponseNamespace="http://progauge.scada.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("tags", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] getTagList([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string equipmentName) {
            object[] results = this.Invoke("getTagList", new object[] {
                        equipmentName});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void getTagListAsync(string equipmentName) {
            this.getTagListAsync(equipmentName, null);
        }
        
        /// <remarks/>
        public void getTagListAsync(string equipmentName, object userState) {
            if ((this.getTagListOperationCompleted == null)) {
                this.getTagListOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTagListOperationCompleted);
            }
            this.InvokeAsync("getTagList", new object[] {
                        equipmentName}, this.getTagListOperationCompleted, userState);
        }
        
        private void OngetTagListOperationCompleted(object arg) {
            if ((this.getTagListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getTagListCompleted(this, new getTagListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://progauge.scada.com", ResponseNamespace="http://progauge.scada.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("tag", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tagItem getTagValueAsOf([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string equipmentName, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string tagName, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] System.DateTime dateTime, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool dateTimeSpecified) {
            object[] results = this.Invoke("getTagValueAsOf", new object[] {
                        equipmentName,
                        tagName,
                        dateTime,
                        dateTimeSpecified});
            return ((tagItem)(results[0]));
        }
        
        /// <remarks/>
        public void getTagValueAsOfAsync(string equipmentName, string tagName, System.DateTime dateTime, bool dateTimeSpecified) {
            this.getTagValueAsOfAsync(equipmentName, tagName, dateTime, dateTimeSpecified, null);
        }
        
        /// <remarks/>
        public void getTagValueAsOfAsync(string equipmentName, string tagName, System.DateTime dateTime, bool dateTimeSpecified, object userState) {
            if ((this.getTagValueAsOfOperationCompleted == null)) {
                this.getTagValueAsOfOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTagValueAsOfOperationCompleted);
            }
            this.InvokeAsync("getTagValueAsOf", new object[] {
                        equipmentName,
                        tagName,
                        dateTime,
                        dateTimeSpecified}, this.getTagValueAsOfOperationCompleted, userState);
        }
        
        private void OngetTagValueAsOfOperationCompleted(object arg) {
            if ((this.getTagValueAsOfCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getTagValueAsOfCompleted(this, new getTagValueAsOfCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://progauge.scada.com", ResponseNamespace="http://progauge.scada.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("tagValues", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tagItem[] getTagValuesAsOf([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string equipmentName, [System.Xml.Serialization.XmlElementAttribute("tagNames", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string[] tagNames, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] System.DateTime dateTime, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool dateTimeSpecified) {
            object[] results = this.Invoke("getTagValuesAsOf", new object[] {
                        equipmentName,
                        tagNames,
                        dateTime,
                        dateTimeSpecified});
            return ((tagItem[])(results[0]));
        }
        
        /// <remarks/>
        public void getTagValuesAsOfAsync(string equipmentName, string[] tagNames, System.DateTime dateTime, bool dateTimeSpecified) {
            this.getTagValuesAsOfAsync(equipmentName, tagNames, dateTime, dateTimeSpecified, null);
        }
        
        /// <remarks/>
        public void getTagValuesAsOfAsync(string equipmentName, string[] tagNames, System.DateTime dateTime, bool dateTimeSpecified, object userState) {
            if ((this.getTagValuesAsOfOperationCompleted == null)) {
                this.getTagValuesAsOfOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTagValuesAsOfOperationCompleted);
            }
            this.InvokeAsync("getTagValuesAsOf", new object[] {
                        equipmentName,
                        tagNames,
                        dateTime,
                        dateTimeSpecified}, this.getTagValuesAsOfOperationCompleted, userState);
        }
        
        private void OngetTagValuesAsOfOperationCompleted(object arg) {
            if ((this.getTagValuesAsOfCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getTagValuesAsOfCompleted(this, new getTagValuesAsOfCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://progauge.scada.com", ResponseNamespace="http://progauge.scada.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("tagValue", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tagItem getTagValueLatest([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string equipmentName, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string tagName) {
            object[] results = this.Invoke("getTagValueLatest", new object[] {
                        equipmentName,
                        tagName});
            return ((tagItem)(results[0]));
        }
        
        /// <remarks/>
        public void getTagValueLatestAsync(string equipmentName, string tagName) {
            this.getTagValueLatestAsync(equipmentName, tagName, null);
        }
        
        /// <remarks/>
        public void getTagValueLatestAsync(string equipmentName, string tagName, object userState) {
            if ((this.getTagValueLatestOperationCompleted == null)) {
                this.getTagValueLatestOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTagValueLatestOperationCompleted);
            }
            this.InvokeAsync("getTagValueLatest", new object[] {
                        equipmentName,
                        tagName}, this.getTagValueLatestOperationCompleted, userState);
        }
        
        private void OngetTagValueLatestOperationCompleted(object arg) {
            if ((this.getTagValueLatestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getTagValueLatestCompleted(this, new getTagValueLatestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://progauge.scada.com", ResponseNamespace="http://progauge.scada.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("tagValues", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tagItem[] getTagValuesLatest([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string equipmentName, [System.Xml.Serialization.XmlElementAttribute("tagNames", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string[] tagNames) {
            object[] results = this.Invoke("getTagValuesLatest", new object[] {
                        equipmentName,
                        tagNames});
            return ((tagItem[])(results[0]));
        }
        
        /// <remarks/>
        public void getTagValuesLatestAsync(string equipmentName, string[] tagNames) {
            this.getTagValuesLatestAsync(equipmentName, tagNames, null);
        }
        
        /// <remarks/>
        public void getTagValuesLatestAsync(string equipmentName, string[] tagNames, object userState) {
            if ((this.getTagValuesLatestOperationCompleted == null)) {
                this.getTagValuesLatestOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTagValuesLatestOperationCompleted);
            }
            this.InvokeAsync("getTagValuesLatest", new object[] {
                        equipmentName,
                        tagNames}, this.getTagValuesLatestOperationCompleted, userState);
        }
        
        private void OngetTagValuesLatestOperationCompleted(object arg) {
            if ((this.getTagValuesLatestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getTagValuesLatestCompleted(this, new getTagValuesLatestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://progauge.scada.com", ResponseNamespace="http://progauge.scada.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("version", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getVersion() {
            object[] results = this.Invoke("getVersion", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getVersionAsync() {
            this.getVersionAsync(null);
        }
        
        /// <remarks/>
        public void getVersionAsync(object userState) {
            if ((this.getVersionOperationCompleted == null)) {
                this.getVersionOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetVersionOperationCompleted);
            }
            this.InvokeAsync("getVersion", new object[0], this.getVersionOperationCompleted, userState);
        }
        
        private void OngetVersionOperationCompleted(object arg) {
            if ((this.getVersionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getVersionCompleted(this, new getVersionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://progauge.scada.com")]
    public partial class tagItem {
        
        private dataType dataTypeField;
        
        private bool dataTypeFieldSpecified;
        
        private string equipmentNameField;
        
        private string nameField;
        
        private System.DateTime timestampField;
        
        private bool timestampFieldSpecified;
        
        private object valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dataType dataType {
            get {
                return this.dataTypeField;
            }
            set {
                this.dataTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataTypeSpecified {
            get {
                return this.dataTypeFieldSpecified;
            }
            set {
                this.dataTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string equipmentName {
            get {
                return this.equipmentNameField;
            }
            set {
                this.equipmentNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timestampSpecified {
            get {
                return this.timestampFieldSpecified;
            }
            set {
                this.timestampFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://progauge.scada.com")]
    public enum dataType {
        
        /// <remarks/>
        STRING,
        
        /// <remarks/>
        INTEGER,
        
        /// <remarks/>
        REAL,
        
        /// <remarks/>
        BOOLEAN,
        
        /// <remarks/>
        DATE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://progauge.scada.com")]
    public partial class getTagValueLatestResponse {
        
        private tagItem tagValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tagItem tagValue {
            get {
                return this.tagValueField;
            }
            set {
                this.tagValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://progauge.scada.com")]
    public partial class getTagValueLatest {
        
        private string equipmentNameField;
        
        private string tagNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string equipmentName {
            get {
                return this.equipmentNameField;
            }
            set {
                this.equipmentNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tagName {
            get {
                return this.tagNameField;
            }
            set {
                this.tagNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://progauge.scada.com")]
    public partial class getVersionResponse {
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://progauge.scada.com")]
    public partial class getVersion {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://progauge.scada.com")]
    public partial class getSystemTimeResponse {
        
        private System.DateTime systemTimeField;
        
        private bool systemTimeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime systemTime {
            get {
                return this.systemTimeField;
            }
            set {
                this.systemTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool systemTimeSpecified {
            get {
                return this.systemTimeFieldSpecified;
            }
            set {
                this.systemTimeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://progauge.scada.com")]
    public partial class getSystemTime {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://progauge.scada.com")]
    public partial class getTagValuesLatest {
        
        private string equipmentNameField;
        
        private string[] tagNamesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string equipmentName {
            get {
                return this.equipmentNameField;
            }
            set {
                this.equipmentNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("tagNames", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] tagNames {
            get {
                return this.tagNamesField;
            }
            set {
                this.tagNamesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://progauge.scada.com")]
    public partial class getEquipmentList {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://progauge.scada.com")]
    public partial class getTagList {
        
        private string equipmentNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string equipmentName {
            get {
                return this.equipmentNameField;
            }
            set {
                this.equipmentNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://progauge.scada.com")]
    public partial class getTagValuesAsOf {
        
        private string equipmentNameField;
        
        private string[] tagNamesField;
        
        private System.DateTime dateTimeField;
        
        private bool dateTimeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string equipmentName {
            get {
                return this.equipmentNameField;
            }
            set {
                this.equipmentNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("tagNames", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] tagNames {
            get {
                return this.tagNamesField;
            }
            set {
                this.tagNamesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime dateTime {
            get {
                return this.dateTimeField;
            }
            set {
                this.dateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateTimeSpecified {
            get {
                return this.dateTimeFieldSpecified;
            }
            set {
                this.dateTimeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://progauge.scada.com")]
    public partial class InvalidTagNameException {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://progauge.scada.com")]
    public partial class DatabaseDownException {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://progauge.scada.com")]
    public partial class getTagValueAsOfResponse {
        
        private tagItem tagField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public tagItem tag {
            get {
                return this.tagField;
            }
            set {
                this.tagField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://progauge.scada.com")]
    public partial class getTagValueAsOf {
        
        private string equipmentNameField;
        
        private string tagNameField;
        
        private System.DateTime dateTimeField;
        
        private bool dateTimeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string equipmentName {
            get {
                return this.equipmentNameField;
            }
            set {
                this.equipmentNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tagName {
            get {
                return this.tagNameField;
            }
            set {
                this.tagNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime dateTime {
            get {
                return this.dateTimeField;
            }
            set {
                this.dateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateTimeSpecified {
            get {
                return this.dateTimeFieldSpecified;
            }
            set {
                this.dateTimeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getEquipmentListCompletedEventHandler(object sender, getEquipmentListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getEquipmentListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getEquipmentListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getSystemTimeCompletedEventHandler(object sender, getSystemTimeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSystemTimeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSystemTimeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.DateTime systemTime {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool systemTimeSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getTagListCompletedEventHandler(object sender, getTagListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getTagListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getTagListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getTagValueAsOfCompletedEventHandler(object sender, getTagValueAsOfCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getTagValueAsOfCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getTagValueAsOfCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public tagItem Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((tagItem)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getTagValuesAsOfCompletedEventHandler(object sender, getTagValuesAsOfCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getTagValuesAsOfCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getTagValuesAsOfCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public tagItem[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((tagItem[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getTagValueLatestCompletedEventHandler(object sender, getTagValueLatestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getTagValueLatestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getTagValueLatestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public tagItem Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((tagItem)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getTagValuesLatestCompletedEventHandler(object sender, getTagValuesLatestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getTagValuesLatestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getTagValuesLatestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public tagItem[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((tagItem[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getVersionCompletedEventHandler(object sender, getVersionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getVersionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getVersionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591